name: Generate README every Month

# https://crontab.guru/#0_0_*_*_1
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile
      - run: yarn start
