name: Manual workflow

on: [repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Manual deploy
        uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn start
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Readme
