name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      dispatcher:
        description: 'Job Dispatcher'
        default: 'Manual'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Manual deploy
        uses: actions/setup-node@v1
      - run: echo "Dispatched from ${{ github.event.inputs.dispatcher }}"
      - run: yarn install --frozen-lockfile
      - run: yarn start
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
